import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Head from 'next/head'
import { marked } from 'marked'
import Link from 'next/link'
import ItemPost from '../../components/ItemPost'
import { slugify } from '../../utils'
// import { NextSeo } from 'next-seo';

export default function tag({ posts }) {




  return (
    <>
   {/* <NextSeo
     title= 'Access your tag realted articles'
     description= 'Access your tag realted articles'
        openGraph={{
          url: 'https://officialrajdeepsingh.dev',
          title: 'Access your tag realted articles',
          description: 'Access your tag realted articles',

          images: [
            {
              url: `${ImageUrl('banner.png')}`,
              width: 1224,
              height: 724,
              alt: 'banner',
              type: 'image/jpeg',
            },
          ],
          site_name: 'Rajdeep Singh',
        }}
      /> */}


<div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='posts'>
        {posts.map((post, index) => (
          <ItemPost key={index} post={post} />
        ))}
      </div>
</div>


      {/* <div className="container my-3">
        <div className="row">

          <div className="col-lg-10 post-date m-1 p-2m-auto">

            {
              posts.map((post, index) => {

                return <ItemPost key={index} post={post} />
              }
              )

            }


          </div>


        </div>
      </div> */}
    </>
  )





}


export async function getStaticPaths() {
  const files = fs.readdirSync(path.join('posts'))
  //console.log(files);
  let tempStorage = []

  const temppaths = files.map((filename) => {
    //console.log(filename);
    const markdownWithMeta = fs.readFileSync(
      path.join('posts', filename),
      'utf-8'
    )
    
    const { data: frontmatter } = matter(markdownWithMeta)
    frontmatter.tags.map(
      tag => {
        //let slug = slugify(tag)
        let slug = tag
        //console.log(slug);
        tempStorage.push({ params: { slug } });
        
      }
    )
    
    

  })

  


  const paths = tempStorage.filter((item,
    index) => {
      //console.log(item);
    return tempStorage.indexOf(item) === index
  })

  //console.log(paths);

  // const paths=["npm"]


  return {
    paths,
    fallback: false,
  }

}

export async function getStaticProps({ params: { slug } }) {

  // Get files from the posts dir
  const files = fs.readdirSync(path.join('posts'))

  let tempStorage = []



  // Get slug and frontmatter from posts

  const tempPosts = files.map((filename) => {

    // Get frontmatter
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    
    const { data: frontmatter } = matter(markdownWithMeta)

    frontmatter.tags.map(
      tag => {
        
        //let tagSlug = slugify(tag)
        let tagSlug = tag
        
        if (slug === tagSlug) {
          
          tempStorage.push({ post: frontmatter })
        }
      }
    )

    
  })

  

  //  remove null in tempPosts 

  const posts = tempStorage.filter(
    post => {
      console.log(post);
      return post && post
    }
  )
  //console.log(posts);
  return {
    props: {
      posts,
    },
  }


}